import Author from "@/authorFooter_component/Author";
import BusinessImage from "@/BusinessImage_component/BusinessImage";
import Introduction from "@/Introduction_component/Introduction";
import Outro from "@/Outro_component/Outro";
import Head from "next/head";

export default function Home() {
  const text = [
    {
      copyright: "Ping",
      facebook: "https://www.facebook.com",
      twitter: "https://www.twitter.com",
      instagram: "https://www.instagram.com",
    },
  ];

  return (
    <>
      <Head>
        <title>Frontend Mentor | Ping coming soon page</title>
        <meta
          name="description"
          content="Frontend Mentor | Ping coming soon page generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="./images/favicon-32x32.png"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossorigin="anonymous"
        />
      </Head>
      <main>
        <Introduction />
        <BusinessImage />
        <Outro
          copyright={text[0].copyright}
          facebook={text[0].facebook}
          twitter={text[0].twitter}
          instagram={text[0].instagram}
        />
      </main>
      <Author />
    </>
  );
}
